---
abstract: 'observation and hook pasteboard changing.'
author:
  - 'OGATA Tetsuji <tetsuji.ogata at gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-Mac-Pasteboard
no_index:
  directory:
    - t
    - inc
requires:
  AnyEvent: 0
  Mac::Pasteboard: 0
  Scalar::Util: 0
  Time::HiRes: 0
resources:
  bugtracker: https://github.com/xtetsuji/p5-AnyEvent-Mac-Pasteboard/issues
  license: http://dev.perl.org/licenses/
  repository: git://github.com/xtetsuji/p5-AnyEvent-Mac-Pasteboard.git
version: 0.01
